#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

# python -u aind-ccf-registration/src/ccf_reg/register.py

python -u main.py --input_data /data/"$1" --input_channel "$2" --input_scale "$3" --input_zarr_directory "$4"
# python -u register_datasets.py