#!/usr/bin/env bash
set -ex

# The previous version of this file was commented-out and follows below:

# python -u aind-ccf-registration/src/ccf_reg/register.py

python -u main.py --input_data /data/"$1" --input_channel "$2".zarr --input_scale "$3" --input_zarr_directory "$4" --bucket_path "$5"
# python -u register_datasets.py
