FROM continuumio/miniconda3:23.9.0-0

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && conda create -n ccf_reg python=3.8 -y

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "ccf_reg", "/bin/bash", "-c"]

RUN pip install -U --no-cache-dir \
    antspyx==0.4.2 \
    argschema==3.0.4 \
    s3fs==2022.11.0 \
    scikit-image==0.19.3 \
    tifffile==2022.10.10 \
    bokeh==2.4.2 \
    zarr==2.13.3 \
    aind-data-schema==1.0.0 \
    xarray_multiscale==1.1.0 \
    dask[distributed]==2022.11.1 \
    matplotlib==3.7.3 \
    ome-zarr==0.8.2 \
    natsort==8.4.0 \
    aicsimageio@git+https://github.com/camilolaiton/aicsimageio.git@feature/zarrwriter-multiscales-daskjobs \
    awscli
